openapi: 3.0.3
info: 
  title: Shop Online APIs Definition
  description: |
   Using this Openapi specification, any consumer can understand the API that are exposed by the Shop-Online team.
  termsOfService: http://hem-kant.blogspot.com/
  contact: 
    name: API Support
    url: http://hem-kant.blogspot.com/
    email: hemkant.india@gmail.com
  license: 
    name: OnlineShop License
    url: http://hem-kant.blogspot.com/
  version: 0.0.1
servers: 
  - url: https://dev.api.com/v1/
    description: Devlopment API
  - url: https://qa.api.com/v1/
    description: QA API
  - url: https://api.com/v1/
    description: PROD API
  - url: https://{username}.api.com:{port}/{version}
    variables:
      username:
        default: demo
        description: this value is a default.
      port:
        enum:
          - "8080"
          - "443"
        default: "8080"
      version: 
        default: v1
      
  
paths: 
  /categories:
    get:
      summary: Returns the list of all products categories
      description: Returns the list of all products and categories which is available on shopOnline portal
      parameters:
        - name: categoryId
          in: query
          schema:
            type: integer
            maximum: 1000
          example: 100
      responses: 
        '200':
          description: A List of catergories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    categoryId:
                      type: integer
                    name:
                      type: string
  /categories/{categoryId}:
    get:
      summary: Returns the list of all products categories
      description: Returns the list of all products and categories which is available on shopOnline portal
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
            maximum: 1000
          example: 100
      responses: 
        '200':
          description: A List of catergories
          content:
            application/json:
              schema:
                type: object
                properties:
                  categoryId:
                    type: integer
                  name:
                    type: string 
        
        