/*
 * Shop Online APIs Definition
 * ## About Us  Using this `OpenAPI specification`, any consumer can understand the _APIs_ that are exposed by the ***Shop-Online*** team.  # Product Categories    - Mobiles      - Apple      - Samsung      - OnePlus    - Laptops    - Watches    - Accessories       - TV      - Home Appliances 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: hemkant.india@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Category;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CategoriesApi
 */
@Ignore
public class CategoriesApiTest {

    private final CategoriesApi api = new CategoriesApi();

    /**
     * Returns the list of all products categories
     *
     * Returns the list of all products and categories  which is available on shopOnline portal 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCategoriesTest() throws Exception {
        Integer categoryId = null;
        List<Category> response = api.getCategories(categoryId);

        // TODO: test validations
    }
    /**
     * Returns the list of all products categories
     *
     * Returns the list of all products and categories which is available on shopOnline portal
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCategoryDetailsTest() throws Exception {
        Integer categoryId = null;
        Category response = api.getCategoryDetails(categoryId);

        // TODO: test validations
    }
}
