/*
 * Shop Online APIs Definition
 * ## About Us  Using this `OpenAPI specification`, any consumer can understand the _APIs_ that are exposed by the ***Shop-Online*** team.  # Product Categories    - Mobiles      - Apple      - Samsung      - OnePlus    - Laptops    - Watches    - Accessories       - TV      - Home Appliances 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: hemkant.india@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse201;
import io.swagger.client.model.OneOfOrdersBody;
import io.swagger.client.model.OrdersBody;
import io.swagger.client.model.OrdersBody1;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OrdersApi
 */
@Ignore
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    /**
     * Get order
     *
     * Get order details based on ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void anyOfOrdersGetTest() throws Exception {
        Integer orderId = null;
        String fetchType = null;
        InlineResponse2001 response = api.anyOfOrdersGet(orderId, fetchType);

        // TODO: test validations
    }
    /**
     * delete order api
     *
     * delete order details
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteOrderDetailsTest() throws Exception {
        Integer orderId = null;
        api.deleteOrderDetails(orderId);

        // TODO: test validations
    }
    /**
     * get order details
     *
     * get order details
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getOrderDetailsTest() throws Exception {
        Integer orderId = null;
        InlineResponse200 response = api.getOrderDetails(orderId);

        // TODO: test validations
    }
    /**
     * Insert oneof the order details
     *
     * Insert oneof the order details in shopping cart
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void oneOfOrdersPostTest() throws Exception {
        OneOfOrdersBody body = null;
        api.oneOfOrdersPost(body);

        // TODO: test validations
    }
    /**
     * order api
     *
     * Post order details for processing 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void saveOrderDetailsTest() throws Exception {
        OrdersBody1 body = null;
        InlineResponse201 response = api.saveOrderDetails(body);

        // TODO: test validations
    }
    /**
     * update order api
     *
     * update order details for processing 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateOrderdetailsTest() throws Exception {
        OrdersBody body = null;
        api.updateOrderdetails(body);

        // TODO: test validations
    }
}
