/*
 * Shop Online APIs Definition
 * ## About Us  Using this `OpenAPI specification`, any consumer can understand the _APIs_ that are exposed by the ***Shop-Online*** team.  # Product Categories    - Mobiles      - Apple      - Samsung      - OnePlus    - Laptops    - Watches    - Accessories       - TV      - Home Appliances 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: hemkant.india@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Products;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ProductsApi
 */
@Ignore
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * Returns the products details
     *
     * Returns the products details based on ID which is available on shopOnline portal
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getProductDetailsTest() throws Exception {
        Integer productsId = null;
        Products response = api.getProductDetails(productsId);

        // TODO: test validations
    }
    /**
     * Returns the list of all products
     *
     * Returns the list of all products which is available on shopOnline portal
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getProductsTest() throws Exception {
        Integer categoryId = null;
        List<Products> response = api.getProducts(categoryId);

        // TODO: test validations
    }
}
